# -*- mode: python ; coding: utf-8 -*-

import os
import sys

ROOT = os.path.dirname(os.path.abspath(SPEC))  # noqa: F821 – PyInstaller provides SPEC

block_cipher = None

a = Analysis(
    ['run_factory_cli.py'],
    pathex=[ROOT],
    binaries=[],
    datas=[
        ('skills', 'skills'),
        ('config', 'config'),
        ('policy.yaml', '.'),
    ],
    hiddenimports=[
        # ── core ──
        'core.agent_runner',
        'core.agent_worker',
        'core.agent_specializer',
        'core.approval_gate',
        'core.ast_engine',
        'core.ast_memory_hub',
        'core.bootstrap_roles',
        'core.builder',
        'core.capability_intent',
        'core.concurrency',
        'core.config_paths',
        'core.control_plane_llm',
        'core.context_window_manager',
        'core.dashboard',
        'core.destructive_guard',
        'core.document_chunker',
        'core.document_index',
        'core.documentation_policy',
        'core.dynamic_orchestrator',
        'core.engine_auth',
        'core.evaluator',
        'core.executor',
        'core.failure_classifier',
        'core.external_skill_candidate_importer',
        'core.external_skill_source_ids',
        'core.external_skill_sources',
        'core.file_io',
        'core.file_lock',
        'core.fsa_loop',
        'core.git_manager',
        'core.hashline_editor',
        'core.ingestion_pipeline',
        'core.install_candidate_utils',
        'core.intent',
        'core.interactive_chat',
        'core.knowledge_skill',
        'core.langchain_adapter',
        'core.llm_engine',
        'core.lsp_bridge',
        'core.manager',
        'core.mcp_adapter',
        'core.memory',
        'core.message_broker',
        'core.model_router',
        'core.policy',
        'core.policy_runtime',
        'core.project_init',
        'core.project_mailbox',
        'core.project_pipeline',
        'core.project_task_board',
        'core.registry',
        'core.registry_manager',
        'core.role_decomposer',
        'core.run_budget',
        'core.runner',
        'core.security_guard',
        'core.security_scanner',
        'core.semantic_embedder',
        'core.skill_autodiscover',
        'core.skill_cache',
        'core.skill_context_config',
        'core.skill_creator',
        'core.skill_enricher',
        'core.skill_eval_harness',
        'core.skill_quality_gate',
        'core.skill_evolution_bus',
        'core.skill_feedback',
        'core.skill_forge',
        'core.skill_loader',
        'core.skill_metadata',
        'core.skill_metadata_adapter',
        'core.skill_preflight',
        'core.skill_procurer',
        'core.skill_promotion',
        'core.skill_registry',
        'core.skill_retrieval_engine',
        'core.skill_spec_synthesizer',
        'core.swarm_council',
        'core.synergy_runner',
        'core.setup_wizard',
        'core.template_input',
        'core.terminal_bridge',
        'core.tool_runtime',
        'core.utils',
        'core.web_search',
        'core.work_item_generator',
        'core.work_item_parser',
        'core.plan_verifier',
        # ── core.continuity ──
        'core.continuity',
        'core.continuity.manifest_store',
        'core.continuity.resume_brief',
        'core.continuity.runtime_paths',
        # ── core.hooks ──
        'core.hooks.base',
        'core.hooks.checkpoint',
        'core.hooks.context_fork',
        'core.hooks.event_bus',
        'core.hooks.guardrails',
        'core.hooks.human_interrupt',
        'core.hooks.langsmith_tracing',
        'core.hooks.lsp_check',
        'core.hooks.memory_consolidation',
        'core.hooks.skill_self_evolution',
        'core.hooks.code_review_doc',
        'core.hooks.design_review_hook',
        'core.design_review_utils',
        'core.review_report',
        'core.review_runner',
        'core.pipeline_quality',
        # ── core.memory_system ──
        'core.memory_system',
        'core.memory_system.models',
        'core.memory_system.facade',
        'core.memory_system.config',
        'core.memory_system.cross_project',
        'core.memory_system.decay',
        'core.memory_system.episode_extractor',
        'core.memory_system.episode_matcher',
        'core.memory_system.graph_builder',
        'core.memory_system.graph_query',
        'core.memory_system.issue_tracker',
        'core.memory_system.knowledge_forger',
        'core.memory_system.knowledge_injection',
        'core.memory_system.project_lifecycle',
        'core.memory_system.router',
        'core.memory_system.adapters',
        'core.memory_system.adapters.base',
        'core.memory_system.adapters.ast_hub',
        'core.memory_system.adapters.continuity',
        'core.memory_system.adapters.core_memory',
        'core.memory_system.adapters.cortex_vector',
        'core.memory_system.adapters.knowledge_graph',
        'core.memory_system.adapters.sync_compyne',
        'core.memory_system.adapters.trace_log',
        # ── core.providers ──
        'core.providers',
        # ── third-party ──
        'yaml',
        'anthropic',
        'google.generativeai',
        'google.genai',
        'openai',
        'langsmith',
        'langchain',
        'langchain_core',
        'langchain_community',
        'tiktoken',
        'tiktoken_ext',
        'tiktoken_ext.openai_public',
        'chromadb',
        'sentence_transformers',
        'pydantic',
        'pydantic.v1',
        'httpx',
        'httpcore',
        'charset_normalizer',
        'certifi',
        'idna',
        'anyio',
        'sniffio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)  # noqa: F821

exe = EXE(  # noqa: F821
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='af',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(  # noqa: F821
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='af',
)
