import argparse
import re
import sys
import subprocess
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
import memory_store as ms


SESSION_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2}) Session\s*$", re.MULTILINE)
TIMELINE_RE = re.compile(r"^- (\d{2}:\d{2}) \[([A-Z0-9_ -]+)\] (.+)$")


@dataclass
class TimelineEntry:
    time_text: str
    entry_type: str
    message: str


@dataclass
class SessionBlock:
    day: date
    header: str
    body: str
    timeline: list[TimelineEntry]


def parse_day(value: str) -> date:
    return datetime.strptime(value, "%Y-%m-%d").date()


def now_day() -> date:
    return datetime.now().date()


def now_hhmm() -> str:
    return datetime.now().strftime("%H:%M")


def section_header(day: date) -> str:
    return f"## {day.isoformat()} Session"


def resolve_project_path(project: str, workspace: str | None) -> Path:
    p = Path(project)
    if p.exists():
        return p.resolve()
    if workspace:
        ws = Path(workspace).resolve()
        if ws.name == project:
            return ws
        candidate = ws / project
        if candidate.exists():
            return candidate
    return p.resolve()


def log_path(project_path: Path) -> Path:
    return project_path / "PROJECT_LOG.md"


def resolve_db_path(db_arg: str | None, workspace: str | None) -> Path:
    if db_arg:
        return Path(db_arg).resolve()
    if workspace:
        return (Path(workspace).resolve() / ".shared_memory" / "shared_memory.db").resolve()
    return (Path(".shared_memory") / "shared_memory.db").resolve()


def ensure_log_file(path: Path) -> None:
    if not path.exists():
        path.write_text("# Project Log\n\n", encoding="utf-8")


def parse_sessions(text: str) -> list[SessionBlock]:
    matches = list(SESSION_RE.finditer(text))
    if not matches:
        return []
    out: list[SessionBlock] = []
    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        header = m.group(0).strip()
        body = text[start + len(m.group(0)) : end]
        day = parse_day(m.group(1))
        timeline: list[TimelineEntry] = []
        for line in body.splitlines():
            mm = TIMELINE_RE.match(line.strip())
            if mm:
                timeline.append(
                    TimelineEntry(
                        time_text=mm.group(1),
                        entry_type=mm.group(2).strip(),
                        message=mm.group(3).strip(),
                    )
                )
        out.append(SessionBlock(day=day, header=header, body=body, timeline=timeline))
    return out


def ensure_day_section(path: Path, day: date) -> None:
    text = path.read_text(encoding="utf-8")
    header = section_header(day)
    if header in text:
        return
    add = (
        f"{header}\n\n"
        "### Timeline\n"
        "- (first entry will be added by save)\n\n"
    )
    if text.endswith("\n"):
        text += add
    else:
        text += "\n\n" + add
    path.write_text(text, encoding="utf-8")


def append_timeline(path: Path, day: date, entry_type: str, message: str, entry_time: str | None = None) -> str:
    ensure_day_section(path, day)
    text = path.read_text(encoding="utf-8")
    header = section_header(day)
    left, right = text.split(header, 1)
    next_idx = right.find("\n## ")
    if next_idx == -1:
        current, rest = right, ""
    else:
        current, rest = right[:next_idx], right[next_idx:]
    if "\n### Timeline\n" not in current:
        current += "\n### Timeline\n"
    ts = entry_time or now_hhmm()
    line = f"- {ts} [{entry_type.upper()}] {message}\n"
    current += line
    path.write_text(left + header + current + rest, encoding="utf-8")
    return ts


def discover_projects(workspace: Path) -> list[Path]:
    projects: list[Path] = []
    if (workspace / ".git").exists() or (workspace / "PROJECT_LOG.md").exists() or (workspace / "README.md").exists():
        projects.append(workspace)
    for d in workspace.iterdir():
        if not d.is_dir():
            continue
        if (d / ".git").exists() or (d / "PROJECT_LOG.md").exists() or (d / "README.md").exists():
            projects.append(d)
    return sorted(projects)


def in_period(day: date, period: str, from_day: date | None, to_day: date | None) -> bool:
    today = now_day()
    if period == "all":
        return True
    if period == "today":
        return day == today
    if period == "7d":
        return today - timedelta(days=6) <= day <= today
    if period == "30d":
        return today - timedelta(days=29) <= day <= today
    if period == "custom":
        if not from_day or not to_day:
            return False
        return from_day <= day <= to_day
    return False


def pick_latest_session(
    sessions: list[SessionBlock],
    explicit_day: date | None,
    period: str,
    from_day: date | None,
    to_day: date | None,
) -> SessionBlock | None:
    if explicit_day:
        for s in sessions:
            if s.day == explicit_day:
                return s
        return None
    candidates = [s for s in sessions if in_period(s.day, period, from_day, to_day)]
    if not candidates:
        return None
    candidates.sort(key=lambda s: s.day)
    return candidates[-1]


def timeline_before_or_equal(entries: list[TimelineEntry], hhmm: str | None) -> list[TimelineEntry]:
    if not hhmm:
        return entries
    return [e for e in entries if e.time_text <= hhmm]


def render_session(session: SessionBlock, hhmm: str | None, mode: str, lines: int) -> str:
    if mode == "session":
        if not hhmm:
            return (session.header + session.body).strip() + "\n"
        # Keep section content and replace timeline with filtered lines.
        filtered = timeline_before_or_equal(session.timeline, hhmm)
        out = [session.header, "", "### Timeline (filtered)"]
        if not filtered:
            out.append(f"- no timeline entry at or before {hhmm}")
        else:
            for e in filtered:
                out.append(f"- {e.time_text} [{e.entry_type}] {e.message}")
        return "\n".join(out).strip() + "\n"

    # mode == timeline
    filtered = timeline_before_or_equal(session.timeline, hhmm)
    if lines > 0:
        filtered = filtered[-lines:]
    head = [session.header, "", "### Timeline"]
    if not filtered:
        head.append("- no matching timeline entries")
    else:
        for e in filtered:
            head.append(f"- {e.time_text} [{e.entry_type}] {e.message}")
    return "\n".join(head).strip() + "\n"


def render_memory_timeline(day: date, entries: list[ms.MemoryEntry], mode: str) -> str:
    head = [section_header(day), "", "### Timeline"]
    if not entries:
        head.append("- no matching timeline entries")
        return "\n".join(head).strip() + "\n"
    for e in entries:
        if mode == "session":
            head.append(f"- {e.entry_time} [{e.entry_type}] {e.message}")
        else:
            head.append(f"- {e.entry_time} [{e.entry_type}] {e.message}")
    return "\n".join(head).strip() + "\n"


def cmd_list_projects(args: argparse.Namespace) -> int:
    workspace = Path(args.workspace).resolve()
    if not workspace.exists():
        print(f"workspace not found: {workspace}")
        return 1
    projects = discover_projects(workspace)
    if not projects:
        print(f"no projects found in: {workspace}")
        return 0
    for p in projects:
        print(p.name)
    return 0


def cmd_save(args: argparse.Namespace) -> int:
    project = resolve_project_path(args.project, args.workspace)
    if not project.exists():
        print(f"project not found: {project}")
        return 1
    path = log_path(project)
    ensure_log_file(path)
    day = parse_day(args.date) if args.date else now_day()
    db_path = resolve_db_path(args.db, args.workspace)
    ts = append_timeline(path, day, args.type, args.message.strip())
    ms.add_entry(db_path, project, day, ts, args.type, args.message.strip(), source="workspace_context_cli")
    print(f"saved: {path} ({day.isoformat()}) + memory({db_path})")
    return 0


def cmd_read(args: argparse.Namespace) -> int:
    project = resolve_project_path(args.project, args.workspace)
    explicit_day = parse_day(args.date) if args.date else None
    from_day = parse_day(args.from_date) if args.from_date else None
    to_day = parse_day(args.to_date) if args.to_date else None
    if args.period == "custom" and (not from_day or not to_day):
        print("custom period requires --from-date and --to-date")
        return 1
    if args.time:
        try:
            datetime.strptime(args.time, "%H:%M")
        except ValueError:
            print("invalid --time format, use HH:MM")
            return 1

    if args.source == "log":
        path = log_path(project)
        if not path.exists():
            print(f"log not found: {path}")
            return 1
        text = path.read_text(encoding="utf-8")
        sessions = parse_sessions(text)
        if not sessions:
            print("no session blocks found")
            return 1
        session = pick_latest_session(sessions, explicit_day, args.period, from_day, to_day)
        if not session:
            print("no matching session for filters")
            return 1
        print(render_session(session, args.time, args.mode, args.lines))
        return 0

    db_path = resolve_db_path(args.db, args.workspace)
    day = ms.pick_latest_session_day(
        db_path=db_path,
        project_path=project,
        explicit_day=explicit_day,
        period=args.period,
        from_day=from_day,
        to_day=to_day,
        today=now_day(),
    )
    if not day:
        print("no matching session for filters")
        return 1
    entries = ms.read_entries_for_day(db_path, project, day, hhmm=args.time, limit=args.lines if args.mode == "timeline" else 0)
    print(render_memory_timeline(day, entries, args.mode))
    return 0


def _run_git(project: Path, *argv: str) -> str:
    try:
        out = subprocess.check_output(["git", *argv], cwd=str(project), text=True, stderr=subprocess.STDOUT)
        return out.strip()
    except Exception:
        return ""


def cmd_auto(args: argparse.Namespace) -> int:
    project = resolve_project_path(args.project, args.workspace)
    if not project.exists():
        print(f"project not found: {project}")
        return 1
    path = log_path(project)
    ensure_log_file(path)
    day = parse_day(args.date) if args.date else now_day()
    db_path = resolve_db_path(args.db, args.workspace)

    branch = _run_git(project, "rev-parse", "--abbrev-ref", "HEAD") or "no-git"
    modified = _run_git(project, "diff", "--name-only")
    staged = _run_git(project, "diff", "--cached", "--name-only")
    untracked = _run_git(project, "ls-files", "--others", "--exclude-standard")

    m_count = len([x for x in modified.splitlines() if x.strip()])
    s_count = len([x for x in staged.splitlines() if x.strip()])
    u_count = len([x for x in untracked.splitlines() if x.strip()])
    user_msg = args.message.strip() if args.message else "auto snapshot"
    summary = f"{user_msg} | branch={branch} | modified={m_count}, staged={s_count}, untracked={u_count}"

    ts = append_timeline(path, day, "AUTO", summary)
    ms.add_entry(db_path, project, day, ts, "AUTO", summary, source="workspace_context_cli:auto")
    print(f"saved auto snapshot: {path} ({day.isoformat()}) + memory({db_path})")
    return 0


def cmd_migrate_log(args: argparse.Namespace) -> int:
    project = resolve_project_path(args.project, args.workspace)
    path = log_path(project)
    db_path = resolve_db_path(args.db, args.workspace)
    if not path.exists():
        print(f"log not found: {path}")
        return 1
    text = path.read_text(encoding="utf-8")
    sessions = parse_sessions(text)
    if not sessions:
        print("no session blocks found")
        return 1
    imported = 0
    for s in sessions:
        for e in s.timeline:
            ms.add_entry(db_path, project, s.day, e.time_text, e.entry_type, e.message, source="project_log_migration")
            imported += 1
    print(f"migrated timeline entries: {imported} -> memory({db_path})")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Workspace-wide context command. Stores logs per project folder."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    ls = sub.add_parser("list-projects", help="List project folders in workspace")
    ls.add_argument("--workspace", default=".", help="Workspace directory path")
    ls.set_defaults(func=cmd_list_projects)

    save = sub.add_parser("save", help="Save timeline entry to a project's PROJECT_LOG.md")
    save.add_argument("message", help="Message text")
    save.add_argument("--project", default=".", help="Project path or project name")
    save.add_argument("--workspace", help="Workspace path for resolving --project by name")
    save.add_argument("--type", default="NOTE", help="Entry type label")
    save.add_argument("--date", help="YYYY-MM-DD (default: today)")
    save.add_argument("--db", help="SQLite DB path (default: <workspace>/.shared_memory/shared_memory.db)")
    save.set_defaults(func=cmd_save)

    read = sub.add_parser("read", help="Read latest context using date/time filters")
    read.add_argument("--project", default=".", help="Project path or project name")
    read.add_argument("--workspace", help="Workspace path for resolving --project by name")
    read.add_argument("--date", help="Exact day: YYYY-MM-DD")
    read.add_argument("--period", default="all", choices=["all", "today", "7d", "30d", "custom"])
    read.add_argument("--from-date", help="YYYY-MM-DD (required when --period custom)")
    read.add_argument("--to-date", help="YYYY-MM-DD (required when --period custom)")
    read.add_argument("--time", help="HH:MM (read state as-of this time)")
    read.add_argument("--mode", default="session", choices=["session", "timeline"])
    read.add_argument("--lines", type=int, default=20, help="Tail lines in timeline mode")
    read.add_argument("--source", default="memory", choices=["memory", "log"], help="Read source")
    read.add_argument("--db", help="SQLite DB path (default: <workspace>/.shared_memory/shared_memory.db)")
    read.set_defaults(func=cmd_read)

    auto = sub.add_parser("auto", help="Auto-save context snapshot from git state")
    auto.add_argument("--project", default=".", help="Project path or project name")
    auto.add_argument("--workspace", help="Workspace path for resolving --project by name")
    auto.add_argument("--message", help="Optional message prefix")
    auto.add_argument("--date", help="YYYY-MM-DD (default: today)")
    auto.add_argument("--db", help="SQLite DB path (default: <workspace>/.shared_memory/shared_memory.db)")
    auto.set_defaults(func=cmd_auto)

    migrate = sub.add_parser("migrate-log", help="Import PROJECT_LOG.md timeline into shared memory")
    migrate.add_argument("--project", default=".", help="Project path or project name")
    migrate.add_argument("--workspace", help="Workspace path for resolving --project by name")
    migrate.add_argument("--db", help="SQLite DB path (default: <workspace>/.shared_memory/shared_memory.db)")
    migrate.set_defaults(func=cmd_migrate_log)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
