"""
skills/research_assistant/skill.py — Himari 기술 리서치 스킬.

v3.1 (2026-04-13): nlm 헬퍼를 core/research_engine.py와 공통화.
중복 구현에 의한 동작 분기를 제거하고 `--mode` 폴백 경로를 자동 승계한다.
설계 문서: docs/features/2026-04-10-setup-wizard-tavily-notebooklm-integration.md §4.9
"""
import os
import json
from datetime import datetime

# NOTE: nlm CLI 헬퍼는 core/research_engine.py로 일원화됨 (af-critic BLOCK-1).
# skill 샌드박스에서도 core 임포트는 정상 동작(project root가 sys.path에 포함됨).
from core.research_engine import (
    _get_archive_notebook_id,
    _nlm_cli,
    query_notebooklm,
)


def _extract_answer(raw_text: str) -> str:
    text = (raw_text or "").strip()
    if not text:
        return ""
    try:
        data = json.loads(text)
        value = data.get("value", {}) if isinstance(data, dict) else {}
        if isinstance(value, dict):
            ans = str(value.get("answer") or "").strip()
            if ans:
                return ans
            raw_response = str(value.get("raw_response") or "").strip()
            if raw_response:
                return raw_response[:2000]
    except Exception:
        pass
    return text


def _query_notebooklm(query: str) -> str:
    """Query NotebookLM archive notebook via shared research_engine helpers.

    core.research_engine.query_notebooklm()이 제공하는 `--mode` 폴백, 인증
    재시도, state 기반 archive 로드를 그대로 승계한다. 결과는 JSON wrapping을
    풀어서 반환(기존 skill 호환).
    """
    target_notebook_id = _get_archive_notebook_id()
    if not target_notebook_id:
        return (
            "(NotebookLM archive 노트북이 구성되지 않았습니다. "
            "`af setup`을 재실행해 아카이브를 설정하세요.)"
        )
    try:
        # query_notebooklm()은 이미 내부에서 _nlm_cli + 인증 재시도 + mode 폴백을
        # 수행한다. 빈 결과(스킵/실패)는 빈 문자열로 반환된다.
        raw = query_notebooklm(query)
        if not raw:
            return "(Error querying NotebookLM: empty response — check `af __check-nlm`)"
        return _extract_answer(raw)
    except Exception as e:
        return f"(Connection Error: {e})"


def propose(ctx):
    return {
        "description": "기술 주제 기반 리서치 보고서를 작성합니다.",
        "required_keys": ["topic"],
        "optional_keys": ["depth", "output_format"],
    }


def apply(ctx):
    try:
        artifacts_dir = ctx.get("artifacts_dir", ".")
        os.makedirs(artifacts_dir, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_{timestamp}.md"
        filepath = os.path.join(artifacts_dir, filename)

        topic = ctx.get("topic") or "General Research"
        research_content = _query_notebooklm(
            f"Detailed research on: {topic}. focus on key technology analysis, pros/cons, and recommendations."
        )

        report_content = f"""# Research Report: {topic}
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Author: Himari (Super Research Architect)

## 1. Executive Summary
(Research based on NotebookLM Secret Archive)

## 2. Key Technology Analysis
{research_content}

## 3. Recommendation
(Review the above analysis and make a decision.)

---
*Generated by Himari Research Skill*
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_content)

        return {
            "ok": True,
            "message": f"Research report generated for '{topic}'",
            "report_path": filepath,
            "content_preview": report_content[:2000],
        }
    except Exception as e:
        return {"ok": False, "error": str(e)}


def test(ctx):
    tmp_ctx = dict(ctx or {})
    tmp_ctx["topic"] = "AI Agent Patterns"
    res = apply(tmp_ctx)
    path = res.get("report_path")
    if res.get("ok") and path and os.path.exists(path):
        try:
            os.remove(path)
        except Exception:
            pass
        return {"ok": True, "message": "Research report generation tested successfully."}
    return res
